use std::sync::{Arc, Mutex};

use anyhow::{Context, Result};
use gstreamer::prelude::*;
use serde::{Deserialize, Serialize};

/// Collected ICE candidate from webrtcbin's "on-ice-candidate" signal.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct IceCandidate {
    pub candidate: String,
    #[serde(rename = "sdpMLineIndex")]
    pub sdp_m_line_index: u32,
}

/// SDP offer or answer.
#[derive(Debug, Serialize, Deserialize)]
pub struct SdpMessage {
    pub sdp: String,
}

/// Shared state for a single WebRTC signaling session.
pub struct SignalingState {
    /// ICE candidates generated by the server (webrtcbin → client).
    pub ice_candidates: Mutex<Vec<IceCandidate>>,
    /// The webrtcbin element from the pipeline.
    pub webrtcbin: gstreamer::Element,
}

impl SignalingState {
    pub fn new(webrtcbin: gstreamer::Element) -> Arc<Self> {
        let state = Arc::new(Self {
            ice_candidates: Mutex::new(Vec::new()),
            webrtcbin,
        });

        // Wire up ICE candidate collection
        let state_weak = Arc::downgrade(&state);
        state
            .webrtcbin
            .connect("on-ice-candidate", false, move |args| {
                if let Some(state) = state_weak.upgrade() {
                    let sdp_m_line_index = args[1]
                        .get::<u32>()
                        .expect("on-ice-candidate arg 1 should be u32");
                    let candidate = args[2]
                        .get::<String>()
                        .expect("on-ice-candidate arg 2 should be String");

                    tracing::debug!(
                        "ICE candidate: mline={} candidate={}",
                        sdp_m_line_index,
                        candidate
                    );

                    if let Ok(mut candidates) = state.ice_candidates.lock() {
                        candidates.push(IceCandidate {
                            candidate,
                            sdp_m_line_index,
                        });
                    }
                }
                None
            });

        // Log ICE connection state changes
        state
            .webrtcbin
            .connect("notify::ice-connection-state", false, move |args| {
                if let Some(element) = args[0].get::<gstreamer::Element>().ok() {
                    if let Ok(state) =
                        element.property_value("ice-connection-state").get::<u32>()
                    {
                        tracing::info!("ICE connection state changed: {}", state);
                    }
                }
                None
            });

        state
    }

    /// Handle an SDP offer from the client and return an SDP answer.
    pub fn handle_offer(&self, offer_sdp: &str) -> Result<String> {
        use gstreamer_sdp::SDPMessage;
        use gstreamer_webrtc::WebRTCSDPType;

        // Parse the SDP offer
        let sdp = SDPMessage::parse_buffer(offer_sdp.as_bytes())
            .map_err(|_| anyhow::anyhow!("Failed to parse SDP offer"))?;
        let offer = gstreamer_webrtc::WebRTCSessionDescription::new(WebRTCSDPType::Offer, sdp);

        // Set remote description
        self.webrtcbin
            .emit_by_name::<()>("set-remote-description", &[&offer, &None::<gstreamer::Promise>]);

        // Create answer synchronously using a promise
        let (sender, receiver) = std::sync::mpsc::channel();
        let promise = gstreamer::Promise::with_change_func(move |reply| {
            let result = if let Ok(Some(reply)) = reply {
                if let Ok(answer) = reply.value("answer") {
                    if let Ok(answer) = answer.get::<gstreamer_webrtc::WebRTCSessionDescription>() {
                        let sdp_text = answer.sdp().to_string();
                        Ok(sdp_text)
                    } else {
                        Err(anyhow::anyhow!("Failed to get WebRTCSessionDescription from answer"))
                    }
                } else {
                    Err(anyhow::anyhow!("No 'answer' field in reply"))
                }
            } else {
                Err(anyhow::anyhow!("Promise returned error or was interrupted"))
            };
            let _ = sender.send(result);
        });

        self.webrtcbin
            .emit_by_name::<()>("create-answer", &[&None::<gstreamer::Structure>, &promise]);

        let answer_sdp = receiver
            .recv_timeout(std::time::Duration::from_secs(10))
            .context("Timeout waiting for SDP answer")?
            .context("Failed to create SDP answer")?;

        // Set local description
        let answer_sdp_msg = SDPMessage::parse_buffer(answer_sdp.as_bytes())
            .map_err(|_| anyhow::anyhow!("Failed to parse generated SDP answer"))?;
        let answer =
            gstreamer_webrtc::WebRTCSessionDescription::new(WebRTCSDPType::Answer, answer_sdp_msg);
        self.webrtcbin
            .emit_by_name::<()>("set-local-description", &[&answer, &None::<gstreamer::Promise>]);

        Ok(answer_sdp)
    }

    /// Add a remote ICE candidate from the client.
    pub fn add_ice_candidate(&self, candidate: &IceCandidate) {
        self.webrtcbin.emit_by_name::<()>(
            "add-ice-candidate",
            &[&candidate.sdp_m_line_index, &candidate.candidate],
        );
        tracing::debug!(
            "Added remote ICE candidate: mline={} candidate={}",
            candidate.sdp_m_line_index,
            candidate.candidate
        );
    }

    /// Drain and return all queued server-side ICE candidates.
    pub fn drain_ice_candidates(&self) -> Vec<IceCandidate> {
        self.ice_candidates
            .lock()
            .map(|mut c| std::mem::take(&mut *c))
            .unwrap_or_default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ice_candidate_serialization() {
        let candidate = IceCandidate {
            candidate: "candidate:1 1 udp 2130706431 192.168.1.1 12345 typ host".into(),
            sdp_m_line_index: 0,
        };
        let json = serde_json::to_string(&candidate).unwrap();
        assert!(json.contains("sdpMLineIndex"));
        assert!(json.contains("candidate:1"));

        let parsed: IceCandidate = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.sdp_m_line_index, 0);
        assert_eq!(parsed.candidate, candidate.candidate);
    }

    #[test]
    fn sdp_message_serialization() {
        let msg = SdpMessage {
            sdp: "v=0\r\n".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: SdpMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.sdp, "v=0\r\n");
    }
}
